version: "2"

run:
  timeout: 10m

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - exptostd
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gosec
    - lll
    - misspell
    - nakedret
    - nilerr
    - reassign
    - revive
    - tagalign
    - testifylint
    - unconvert
    - unparam
    - wastedassign
    - whitespace

  settings:
    funlen:
      lines: 60
      statements: 40
    gocyclo:
      # minimal code complexity to report, 30 by default (but we recommend 10-20)
      min-complexity: 11
    gocognit:
      # minimal code complexity to report, 30 by default (but we recommend 10-20)
      min-complexity: 10
    gosec:
      severity: medium
    lll:
      line-length: 140
    tagalign:
      align: true
      sort: false
      strict: false

  exclusions:
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      # Exclude test functions from linting rules
      - source: "Test.*"
        linters:
          - funlen
          - gocognit
          - gocyclo
          - dogsled
      # Exclude linters from running on tests files.
      - path: _test\.go
        linters:
          - revive
          - bodyclose

formatters:
  enable:
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/gesundheitscloud/
    golines:
      max-len: 140

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
  fix: true

severity:
  default: error
